### ISSUE TITLE
Wheel for 0.9.0?

### ISSUE THREAD

**Issue by dstufft** [mozilla-services/pyramid_multiauth#16]
pyramid_multiauth 0.8.0 had a universal wheel published while 0.9.0 does not. Is this an accidental oversight or explicit decision? If the former it'd be great to get a wheel uploaded.

**Comment by rfk** [comment]
Accidental, thanks for pointing it out.

**Comment by rfk** [comment]
OK, wheel should be back now, thanks again @dstufft!
