### ISSUE TITLE
We detect a strange WWW-Authenticate header syntax when using multiauth

### ISSUE THREAD

**Issue by Natim** [mozilla-services/pyramid_multiauth#9]
See https://github.com/mozilla-services/cliquet-fxa/issues/9

**Comment by rfk** [comment]
We don't formulate any WWW-Authentiate headers ourselves, but we do combine the headers sent by each of the subordinate auth policies.  Perhaps this is a header-formatting bug in one of those policies that makes it break when combined with other headers?

**Comment by rfk** [comment]
@natim it would be great if you could factor out a testcase for this

**Comment by Natim** [comment]
> it would be great if you could factor out a testcase for this

Yes let's do that :+1: but I think it is a matter of missing space on WWW-Authenticate concatenation.

**Comment by rfk** [comment]
> WWW-Authenticate concatenation

I had a poke around in various codebases, but it wasn't obvious to me where this concatenation actually occurs.

**Comment by Natim** [comment]
As far as I can tell, it seems that all AuthenticationPolicies``forget`` method are returning a list containing ``[('WWW-Authenticate', 'Basic realm="Realm"')]`` and that at some point the response headerlist is converted into a unique header.

I was looking at [webob](https://github.com/Pylons/webob/blob/master/webob/response.py#L231) but it wasn't clear to me where was the concatenation being made.

**Comment by Natim** [comment]
I can confirm that running directly with waitress, I've got the following: (which are valid)

```
http GET http://localhost:8888/v1/buckets/default
HTTP/1.1 401 Unauthorized
Access-Control-Expose-Headers: Backoff,Retry-After,Alert,Content-Length
Content-Length: 110
Content-Type: application/json; charset=UTF-8
Date: Wed, 30 Sep 2015 08:21:59 GMT
Server: waitress
Www-Authenticate: Bearer realm="Realm"
Www-Authenticate: Basic realm="Realm"

{
    "code": 401, 
    "errno": 104, 
    "error": "Unauthorized", 
    "message": "Please authenticate yourself to use this endpoint."
}
```
